//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlzAdmininstration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poll()
        {
            this.Users = new HashSet<User>();
        }
    
        public long PollId { get; set; }
        public string Argument { get; set; }
        public short ReportCount { get; set; }
        public bool PollStatus { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public short CategoryCategoryId { get; set; }
        public long Option_OptionsId { get; set; }
        public long Twitter_TwitterId { get; set; }
        public long Facebook_FacebookId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Facebook Facebook { get; set; }
        public virtual Option Option { get; set; }
        public virtual Twitter Twitter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
