//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlzAdmininstration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vote()
        {
            this.Options = new HashSet<Option>();
        }
    
        public long VotesId { get; set; }
        public long Vote1 { get; set; }
        public long Vote2 { get; set; }
        public Nullable<long> Vote3 { get; set; }
        public Nullable<long> Vote4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Option> Options { get; set; }
    }
}
